# file name: problemSetDay2.py
name = input('''what is your name?''')
print(name)
birthday = input('''when is your birthday?''')
print(birthday)
grade = input('''what grade are you in?''')
print(grade)
school = input('''what school are you in?''')
print(school)
Favorite = input('''what is your favorite subject?''')
print(Favorite)
whatdoyouwanttobe = input('''what do you want to be whan you grow up?''')
print(whatdoyouwanttobe)
b= input("what is the value of b?")
#b = int(input("what is the value of b?"))
print(b)
a= input("what is the value of a?")
#a = int(input("what is the value of a?"))
print(a)
c= input("what is the value of c?")
#c = int(input("what is the value of c?"))
print(c)
x= input("what is x?")
#x = int(input(([b*-1+/- sqrt(b^2-4ac)]/2a)))
print(x)